
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.28.1.  DO NOT EDIT!
//*************************************************************************************

namespace XTC.FMP.MOD.ImageAtlas3D.LIB.Bridge
{
    /// <summary>
    /// 数据传输对象
    /// </summary>
    public interface IDTO
    {
    }
}
