
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.30.1.  DO NOT EDIT!
//*************************************************************************************
public abstract class IntegrationTestBase
{
    [Fact]
    public abstract Task Test();
}
